# Generated by Django 4.0.1 on 2022-01-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='points',
            field=models.IntegerField(),
        ),
    ]
