# Generated by Django 4.0.1 on 2022-01-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_spend_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='remaining_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
