# Generated by Django 4.0.1 on 2022-01-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0005_transaction_remaining_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='receipt',
            field=models.JSONField(default=0),
        ),
    ]
