# Generated by Django 4.0.1 on 2022-01-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0008_alter_payer_total_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payer',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
